---
- name: Create 99-restrict_dangerous_execution_pattern.conf
  copy:
    dest: /etc/sysctl.d/99-restrict_dangerous_execution_pattern.conf
    content: |
        # Disable core dumps
        fs.suid_dumpable = 0
        # Disable System Request debugging functionality
        kernel.sysrq = 0
        # Restrict access to kernel logs
        kernel.dmesg_restrict = 1
        # Randomise memory space
        kernel.randomize_va_space = 2
        # Hide kernel pointers
        kernel.kptr_restrict = 2
- name: Update 99-restrict_dangerous_execution_pattern.conf
  file:
    dest: /etc/sysctl.d/99-restrict_dangerous_execution_pattern.conf
    mode: '0644'

- name: Create 20-prevent_dos.conf
  copy:
    dest: /etc/security/limits.d/20-prevent_dos.conf
    content: |
        # Disabling core dumps
        *  soft core 0
        *  hard  core  0
                
        *  soft   nofile    4096
        *  hard   nofile    65536
        *  soft   nproc     4096
        *  hard   nproc     4096
        *  soft   locks     4096
        *  hard   locks     4096
        *  soft   stack     10240
        *  hard   stack     32768
        *  soft   memlock   64
        *  hard   memlock   64
        *  hard   maxlogins 5
        
        # Soft limit 32GB, hard 64GB
        *  soft   fsize     33554432
        *  hard   fsize     6710886
        
        # Limits for root
        #   root   soft   nofile    4096
        #   root   hard   nofile    65536
        #   root   soft   nproc     4096
        #   root   hard   nproc     4096
        #   root   soft   stack     10240
        #   root   hard   stack     32768
        #   root   soft   fsize     3355443
- name: Update 20-prevent_dos.conf
  file:
    path: /etc/security/limits.d/20-prevent_dos.conf
    mode: '0644'

- name: Create 99-networking.conf
  copy:
    dest: /etc/sysctl.d/99-networking.conf
    content: |
        ### GENERAL NETWORK SECURITY OPTIONS

        #Prevent SYN attack, enable SYNcookies (they will kick-in when the max_syn_backlog reached)
        net.ipv4.tcp_syncookies = 1
        net.ipv4.tcp_syn_retries = 2
        net.ipv4.tcp_synack_retries = 2
        net.ipv4.tcp_max_syn_backlog = 4096

        # Disables packet forwarding
        net.ipv4.ip_forward = 0
        net.ipv4.conf.all.forwarding = 0
        net.ipv4.conf.default.forwarding = 0
        net.ipv6.conf.all.forwarding = 0
        net.ipv6.conf.default.forwarding = 0

        # Disables IP source routing
        net.ipv4.conf.all.send_redirects = 0
        net.ipv4.conf.default.send_redirects = 0
        net.ipv4.conf.all.accept_source_route = 0
        net.ipv4.conf.default.accept_source_route = 0
        net.ipv6.conf.all.accept_source_route = 0
        net.ipv6.conf.default.accept_source_route = 0

        # Enable IP spoofing protection, turn on source route verification
        net.ipv4.conf.all.rp_filter = 1
        net.ipv4.conf.default.rp_filter = 1

        # Disable ICMP Redirect Acceptance
        net.ipv4.conf.all.accept_redirects = 0
        net.ipv4.conf.default.accept_redirects = 0
        net.ipv4.conf.all.secure_redirects = 0
        net.ipv4.conf.default.secure_redirects = 0
        net.ipv6.conf.all.accept_redirects = 0
        net.ipv6.conf.default.accept_redirects = 0

        # Enable Log Spoofed Packets, Source Routed Packets, Redirect Packets
        net.ipv4.conf.all.log_martians = 1
        net.ipv4.conf.default.log_martians = 1

        # Don't relay bootp
        net.ipv4.conf.all.bootp_relay = 0

        # Don't proxy arp for anyone
        net.ipv4.conf.all.proxy_arp = 0

        # Turn on the tcp_timestamps
        net.ipv4.tcp_timestamps = 1

        # Don't ignore directed pings
        net.ipv4.icmp_echo_ignore_all = 0

        # Enable ignoring broadcasts request
        net.ipv4.icmp_echo_ignore_broadcasts = 1

        # Enable bad error message Protection
        net.ipv4.icmp_ignore_bogus_error_responses = 1

        # Allowed local port range
        net.ipv4.ip_local_port_range = 16384 65535

        # Enable a fix for RFC1337 - time-wait assassination hazards in TCP
        net.ipv4.tcp_rfc1337 = 1
- name: Update 99-networking.conf
  file:
    path: /etc/sysctl.d/99-networking.conf
    mode: '0644'

- name: Create 99-hardening.conf
  copy:
    dest: /etc/modprobe.d/99-hardening.conf
    content: |
        install cramfs /bin/true
        install freevxfs /bin/true
        install jffs2 /bin/true
        install hfs /bin/true
        install hfsplus /bin/true
        install squashfs /bin/true
        install udf /bin/true
        install fat /bin/true         ### comment out this line for VMware servers
        install vfat /bin/true       ### comment out this line for VMware servers
        install cifs /bin/true
        install nfs /bin/true
        install nfsv3 /bin/true
        install nfsv4 /bin/true
        install gfs2 /bin/true

        #Prevent i2c_piix4 module
        blacklist i2c_piix4
        
        #Prevent Users Mounting USB Storage
        blacklist usb-storage
        blacklist firewire-core
        install usb-storage /bin/tru
        
        #Disable (uncommon) protocols
        install dccp /bin/true
        install sctp /bin/true
        install rds /bin/true
        install tipc /bin/true
- name: Update 99-hardening.conf
  file:
    path: /etc/modprobe.d/99-hardening.conf
    mode: '0644'